spring:
  datasource:
    url: ($JDBC_DATABSE_URL)
    driver-class-name: com.mysql.jdbc.Driver
    username: ($JDBC_DATABSE_USERNAME)
    password: ($JDBC_DATABSE_PASSWORD)
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: "614d6786aedcec"
    password: "b9621795034755"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
email:
  subject: "Parcel delivered"
  message: "Parcel has been delivered to: %s"
  from: "logistics@prod.com"
